# Generated by Django 4.2.30 on 2026-05-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdefinition',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, help_text='Subset of station roles. If blank, any station role can execute.', related_name='executable_tasks', to='auth.group'),
        ),
    ]
