# Generated by Django 4.2.30 on 2026-05-24 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstancehistory',
            name='from_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_from', to='workflows.station'),
        ),
        migrations.AddField(
            model_name='workflowinstancehistory',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='instances.workflowinstance'),
        ),
        migrations.AddField(
            model_name='workflowinstancehistory',
            name='task_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflows.taskdefinition'),
        ),
        migrations.AddField(
            model_name='workflowinstancehistory',
            name='task_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instances.taskexecution'),
        ),
        migrations.AddField(
            model_name='workflowinstancehistory',
            name='to_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_to', to='workflows.station'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='current_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_instances', to='workflows.station'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflowtemplateversion'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='instances.workflowinstance'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_executions', to='workflows.station'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='task_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='workflows.taskdefinition'),
        ),
        migrations.AddIndex(
            model_name='workflowinstancehistory',
            index=models.Index(fields=['instance', '-timestamp'], name='instances_w_instanc_98d318_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstancehistory',
            index=models.Index(fields=['action'], name='instances_w_action_91881c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status'], name='instances_w_status_19598b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['current_station'], name='instances_w_current_5994c6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['reference'], name='instances_w_referen_75cd38_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status', 'current_station'], name='instances_w_status_79a185_idx'),
        ),
    ]
