# Generated by Django 4.2.30 on 2026-05-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='public_token',
            field=models.UUIDField(db_index=True, help_text='Shareable token for standalone instance view. Validates station roles.', null=True, unique=True),
        ),
    ]
