# Generated by Django 4.2.30 on 2026-05-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='body_html',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='cc_emails',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='subject',
        ),
        migrations.AddField(
            model_name='notification',
            name='instance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INSTANCE_ASSIGNED', 'Instance Assigned'), ('TASK_READY', 'Task Ready'), ('TASK_COMPLETED', 'Task Completed'), ('INSTANCE_MOVED', 'Instance Moved'), ('INSTANCE_COMPLETED', 'Instance Completed'), ('INSTANCE_CANCELLED', 'Instance Cancelled')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
    ]
